name: Hello

on:
  push:
    branches: [main]

jobs:
  greet:
    runs-on: ubuntu-latest

    steps:
      - name: Say hello to user
        run: echo "hello user"
  show-version:
    runs-on: ubuntu-latest
    steps:
      - name: show python and docker version
        run: python --version && docker --version
    
